CREATE TABLE SUMMER_SCHOOL_RENTALS (
    PROPERTY_ID NUMERIC PRIMARY KEY,
    OFFICE_NUM NUMERIC,
    ADDRESS varchar(100),
    SQR_FT smallint,
    FLOORS tinyint,
    WEEKLY_RENT smallint,
    OWNER_NUM char(5)
);

INSERT INTO SUMMER_SCHOOL_RENTALS (PROPERTY_ID, OFFICE_NUM, ADDRESS, SQR_FT, FLOORS, WEEKLY_RENT,OWNER_NUM)
VALUES
(13, 1, '5867 Goodwin Ave', '1650', '1', '400', 'CO103');